### ISSUE TITLE
Desktop not showing correctly in QEMU

### ISSUE THREAD

**Issue by yeppiidev** [AlgorithMan-de/wyoos#21]
The desktop and windows are not showing correctly in QEMU

**Comment by holysheep015** [comment]
qemu has a lot of problems with this OS dude, use virtualbox or something

**Comment by rawdevelop** [comment]
@yeppiidev i use QEmu and it shows all correctly from ISO file and BIN

**Comment by yeppiidev** [comment]
For me, it didn't and I'm not really tinkering with it anymore so I guess imma close this issue.
