### ISSUE TITLE
Graphics mode is not working on qemu.

### ISSUE THREAD

**Issue by tigertv** [AlgorithMan-de/wyoos#23]
I don't see windows on screen in `GRAPHICSMODE`.
I've used `qemu-system-i386`.

**Comment by yeppiidev** [comment]
Use VirtualBox and see if it works.

**Comment by tigertv** [comment]
Have you tried that?

**Comment by yeppiidev** [comment]
Yes

**Comment by holysheep015** [comment]
qemu has a lot of problems with this OS dude, use virtualbox or something
