### ISSUE TITLE
FATAL: Could not read from the boot medium! System halted.

### ISSUE THREAD

**Issue by nerososft** [AlgorithMan-de/wyoos#7]

**Comment by nerososft** [comment]
I can't find grub-legacy, so I installed grub.

**Comment by nerososft** [comment]
I don't know how to solve this problem, em..., can you help me

**Comment by nerososft** [comment]
I have solved it by install grub2. thank u

**Comment by hulous** [comment]
Thank you @nerososft to have shared this, it works for me too ! :+1:
