### ISSUE TITLE
Make Kernel.o error

### ISSUE THREAD

**Issue by ghost** [AlgorithMan-de/wyoos#8]
make kernel.o
make: *** No rule to make target 'kernel.o'.  Stop.

I'm in part one 
https://www.youtube.com/watch?v=1rnA6wpF0o4&t=746s

any help with this error would be greatly appreciated I'm assuming it's a error in the makefile

**Comment by AlgorithMan-de** [comment]
[http://lmgtfy.com/?q=make%3A+***+No+rule+to+make+target](http://lmgtfy.com/?q=make%3A+***+No+rule+to+make+target)

**Comment by ghost** [comment]
Thank you when I originally posted the question that was my first  real attempt at any programming in general if anyone runs into this problem I would suggest getting the version of mint being used in the video and compile from their i actually did this a few weeks ago and it worked then ive had internet problems and I literally just back up and running I'm going to bed tonight but tomorrow im going to come back with the correct version of mint and all the tool version number we know that works and seeing as Ubuntu 18.04 is out I I'm also going to see if this has been resolved their and do further testing and debugging to isolate the problem for everyone else.

P.S. Google didn't help
